[project]
name = "arcade_cabinet_LeftOverDefault"
version = "0.0.0.9"
authors = [
    { name="LeftOverDefault", email="michaelgoddard@outlook.com" },
]
description = "Python Game Development Library"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 1 - Planning",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License (GPL)",
    "Operating System :: Microsoft :: Windows",
    "Topic :: Games/Entertainment"
]
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project.urls]
Homepage = "https://github.com/LeftOverDefault/The-Arcade-Cabinet"
Issues = "https://github.com/LeftOverDefault/The-Arcade-Cabinet/issues"